baseurl = "http://superpeteblaze.github.io/"
title = "Pete Smith"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Pete Smith"
googleAnalytics = "UA-73366940-2"
disqusShortname = "petethedeveloper"

[Author]
    name = "Pete Smith"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Pete Smith"
    description = "Swift - iOS - Engineering"
    github = "https://www.github.com/superpeteblaze"
    linkedin = "https://ie.linkedin.com/in/petethedeveloper"
    twitter = "https://www.twitter.com/superpeteblaze"
    stackoverflow = "http://stackexchange.com/users/294929/superpeteblaze"
    email = "peadar81@gmail.com"
    opengraph = true

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Apps"
    url = "/apps/"
    weight = 2

[[menu.main]]
    name = "Opensource"
    url = "/opensource/"
    weight = 3
