# Site settings
baseurl = "http://superpeteblaze.github.io/"
languageCode = "en-us"
title = "Pete Smith"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-73366940-2"
# Disable comments by leaving disqusShortname empty
disqusShortname = "petethedeveloper"

[params]
	name = "Pete Smith"
	description = "I'm Pete, an Enginner and iOS Developer, and this is my personal site where I blog and reference my projects"
	bio = "Swift - iOS - Engineering"
	# Enter optionally your twitter account
	twitter = "superpeteblaze"
	enableRSS = false

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	apps = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm Pete, an Enginner and iOS Developer"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
		stackoverflow = "http://stackexchange.com/users/294929/superpeteblaze"
    twitter  = "https://www.twitter.com/superpeteblaze"
    facebook = "https://www.facebook.com/superpeteblaze"
    github   = "https://www.github.com/superpeteblaze"
