# Site settings
baseurl = "http://superpeteblaze.github.io/"
languageCode = "en-us"
title = "Pete Smith"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-73366940-2"
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Pete Smith"
	description = "Swift - iOS - Engineering"
	bio = "Swift - iOS - Engineering"
	# Enter optionally your twitter account
	twitter = "https://www.twitter.com/superpeteblaze"
	enableRSS = false

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
  about = "About"
	apps = "Apps"
	opensource = "Open source"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm Pete, an engineer and iOS developer"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/superpeteblaze"
    github   = "https://www.github.com/superpeteblaze"
